import {
  KeyRound,
  Laptop,
  AppWindow,
  Network,
  ClipboardList,
  CircleEllipsis,
  LockKeyhole,
  UserCheck,
  UserPlus,
  ShieldCheck,
  Fingerprint,
  Monitor,
  Printer,
  Keyboard,
  Phone,
  Smartphone,
  ServerCrash,
  Bug,
  Hourglass,
  Unplug,
  Settings,
  LifeBuoy,
  WifiOff,
  Wifi,
  Server,
  Router,
  Ban,
  Download,
  Wrench,
  PackagePlus,
  FilePen,
  ClipboardPlus,
  HelpCircle,
  BookOpen,
  TriangleAlert,
  MoreHorizontal,
} from 'lucide-react';

// Registry explícito (só os ícones usados → tree-shaking). O nome vem do banco
// (ticket_categories.icon / ticket_subcategories.icon) e é resolvido aqui.
// Usar SEMPRE a mesma lib (lucide-react) já presente no projeto.
const ICONS = {
  KeyRound,
  Laptop,
  AppWindow,
  Network,
  ClipboardList,
  CircleEllipsis,
  LockKeyhole,
  UserCheck,
  UserPlus,
  ShieldCheck,
  Fingerprint,
  Monitor,
  Printer,
  Keyboard,
  Phone,
  Smartphone,
  ServerCrash,
  Bug,
  Hourglass,
  Unplug,
  Settings,
  LifeBuoy,
  WifiOff,
  Wifi,
  Server,
  Router,
  Ban,
  Download,
  Wrench,
  PackagePlus,
  FilePen,
  ClipboardPlus,
  HelpCircle,
  BookOpen,
  TriangleAlert,
  MoreHorizontal,
} as const;

export function CategoryIcon({ name, className }: { name: string; className?: string }) {
  const Icon = ICONS[name as keyof typeof ICONS] ?? HelpCircle;
  return <Icon className={className} aria-hidden />;
}
